import { ambiColors, ambiMotion, watchFace } from "./ambi";
import { duration, easing } from "./motion";
import { darkColorOverrides, darkHairlineRing } from "./themes";
import {
  breakpoints,
  colors,
  containers,
  controlHeights,
  elevation,
  fontStacks,
  fontWeights,
  hairlineRing,
  radius,
  spacing,
  typography,
  type ElevationName,
} from "./vercel";

const px = (value: number) => (value === 0 ? "0" : `${value}px`);

/**
 * Tailwind namespaces cleared so only design-system tokens produce utilities
 * (e.g. no `bg-red-500`, no `font-bold`).
 */
const resetNamespaces = [
  "color",
  "font",
  "font-weight",
  "text",
  "radius",
  "shadow",
  "inset-shadow",
  "drop-shadow",
  "text-shadow",
  "breakpoint",
  "container",
  "tracking",
  "leading",
  "ease",
];

function elevationValue(name: ElevationName, ring: string): string {
  const level = elevation[name];
  if (!level.ring) return level.light;
  return level.light ? `${level.light}, ${ring}` : ring;
}

function declarations(entries: [string, string][], indent = "  "): string[] {
  return entries.map(([name, value]) => `${indent}--${name}: ${value};`);
}

export function buildTokensCss(): string {
  const theme: [string, string][] = [
    ...resetNamespaces.map((ns): [string, string] => [`${ns}-*`, "initial"]),
    ["font-sans", fontStacks.sans],
    ["font-mono", fontStacks.mono],
    ...Object.entries(fontWeights).map(([name, value]): [string, string] => [`font-weight-${name}`, String(value)]),
    ...Object.entries(colors).map(([name, value]): [string, string] => [`color-${name}`, value]),
    ...Object.entries(ambiColors).map(([name, token]): [string, string] => [`color-${name}`, token.value]),
    ...Object.entries(typography).flatMap(([name, style]): [string, string][] => [
      [`text-${name}`, px(style.fontSize)],
      [`text-${name}--line-height`, px(style.lineHeight)],
      [`text-${name}--letter-spacing`, px(style.letterSpacing)],
      [`text-${name}--font-weight`, String(style.fontWeight)],
    ]),
    ...Object.entries(radius).map(([name, value]): [string, string] => [`radius-${name}`, px(value)]),
    ["spacing", "4px"],
    ...Object.entries(spacing).map(([name, value]): [string, string] => [`spacing-${name}`, px(value)]),
    ...Object.entries(controlHeights).map(([name, value]): [string, string] => [`spacing-control-${name}`, px(value)]),
    ...Object.entries(breakpoints).map(([name, value]): [string, string] => [`breakpoint-${name}`, px(value)]),
    ...Object.entries(containers).map(([name, value]): [string, string] => [`container-${name}`, px(value)]),
    ...Object.entries(easing).map(([name, value]): [string, string] => [`ease-${name}`, value]),
    ["default-transition-duration", duration.fast],
    ["default-transition-timing-function", easing.standard],
  ];

  const root: [string, string][] = [
    ...Object.entries(duration).map(([name, value]): [string, string] => [`duration-${name}`, value]),
    ...(Object.keys(elevation) as ElevationName[]).map((name): [string, string] => [
      `elevation-${name}`,
      elevationValue(name, hairlineRing),
    ]),
    ...Object.entries(watchFace).map(([name, token]): [string, string] => [`watch-face-${name}`, token.value]),
    ...Object.entries(ambiMotion).map(([name, token]): [string, string] => [`watch-motion-${name}`, token.value]),
  ];

  const dark: [string, string][] = [
    ...Object.entries(darkColorOverrides).map(([name, value]): [string, string] => [`color-${name}`, value]),
    ...(Object.keys(elevation) as ElevationName[]).map((name): [string, string] => [
      `elevation-${name}`,
      elevationValue(name, darkHairlineRing),
    ]),
  ];

  const utilities = (Object.keys(elevation) as ElevationName[]).map(
    (name) => `@utility elevation-${name.replace("level-", "")} {\n  box-shadow: var(--elevation-${name});\n}`,
  );

  return [
    "/* Generated by scripts/build-tokens.ts from src/tokens. Do not edit by hand. */",
    "",
    "@theme static {",
    ...declarations(theme),
    "}",
    "",
    ":root {",
    "  color-scheme: light;",
    ...declarations(root),
    "}",
    "",
    '[data-theme="dark"] {',
    "  color-scheme: dark;",
    ...declarations(dark),
    "}",
    "",
    ...utilities.flatMap((utility) => [utility, ""]),
  ].join("\n");
}
